<?php declare(strict_types = 1);

/**
 * @file
 * Primary module hooks for School module.
 */

/**
 * Implements hook_entity_bundle_info_alter().
 */
function school_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['article'])) {
    // phpcs:ignore Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing
    $bundles['node']['article']['class'] = \Drupal\school\Entity\Node\Article::class;
  }
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function school_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['custom_entity_example']['default'])) {
    // phpcs:ignore Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing
    $bundles['custom_entity_example']['default']['class'] = \Drupal\school\Entity\CustomEntityExample\SchoolEntity::class;
  }
}
