paypaytm.paypaytm_gateway.plugin.paytm_payment:
  type: paypaytm_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant Id'
    merchant_key:
      type: string
      label: 'Merchant Key'
    merchant_website:
      type: string
      label: 'Merchant Website'